---
- hosts: linuxservers
  become: yes

  tasks:
  - name: Ensure group developers exists
    group:
      name: "{{ item }}"
      state: present
    loop:
      - It
      - Developers
      - Finance
      - Management

  - name: Create Users
    ansible.builtin.user:
      name: "{{ item.name }}"
      group: "{{ item.groups }}"
      state: "{{ item.state }}"
    loop:
      - { name: 'homer', groups: 'Developers' , state: 'present' }
      - { name: 'bart', groups: 'It' , state: 'present' }
      - { name: 'lisa', groups: 'Management', state: 'present' }
      - { name: 'ned', groups: 'Finance', state: 'present' }
      - { name: 'moe', groups: 'Developers', state: 'absent'}
